#! /opt/homebrew/bin/php
<?php
require_once(__DIR__ . "/../vendor/autoload.php"); // FIXME (see v2cli script)


use vertwo\plite\CommandLine\CLI;
use function vertwo\plite\clog;



class driver extends CLI
{
    protected function getShortOpts () { return ""; }
    
    
    public function main ()
    {
        clog("Hello, world!");
        return 0;
    }
}


driver::run();
